name: app_habitcrew
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  particles_flutter: ^2.0.0
  iconify_flutter: ^0.0.7
  flutter_custom_clippers: ^2.1.0
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  simple_animations: ^5.2.0
  confetti: ^0.8.0
  image_picker: ^1.1.2
  crop_image: ^1.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/