#org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=384m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=C:\\Users\\h.alvarez\\Documents\\jdk-17.0.18+8
android.experimental.legacyTransform.forceNonIncremental=true
android.desugarJdkLibs=com.android.tools:desugar_jdk_libs:2.1.4