# Aumento de RAM para evitar el error de "Java heap space"
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true

# Ajustes de AndroidX y SDK
android.useAndroidX=true
android.enableJetifier=true
android.suppressUnsupportedCompileSdk=36
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr

# Compatibilidad de recursos
android.nonTransitiveRClass=false
android.nonFinalResIds=false